name: Build Dictionary

permissions:
  contents: write

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'         # Matches version tags like v1.0.0, v2.3.1
    paths:
      - 'drafts/**'
      - 'code/**'
      - 'scripts/generate_preview.py'

  release:
    types: [published]

  workflow_dispatch:

jobs:
  preview:
    name: Generate Previews
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyyaml rdflib || true

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin git@github.com:burespe1/semantic-dictionary.git
          git fetch origin
          git checkout main
          git reset --hard origin/main

      - name: Run Preview Script
        run: python scripts/generate_preview.py

      - name: Commit and Push Preview Files
        run: |
          git add -f preview/
          git add -f drafts/INDEX.md
          git diff --cached --quiet || git commit -m "🔄 Updated preview files"
          git push --force-with-lease origin main

  release:
    name: Generate Release
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyyaml rdflib || true

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin git@github.com:burespe1/semantic-dictionary.git
          git fetch origin
          git checkout main
          git reset --hard origin/main

      - name: Run Release Script
        run: python scripts/generate_release.py

      - name: Commit and Push Release Files
        run: |
          git add -f release/
          git add -f vocab/
          git diff --cached --quiet || git commit -m "🔄 Updated release files"
          git push --force-with-lease origin main

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "📦 Release ${{ github.ref_name }}"
          body: "Automated release for version ${{ github.ref_name }}"
          files: release/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}